FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev gcc curl && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir poetry==2.1.3

COPY pyproject.toml poetry.lock README.md ./
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

COPY . .
RUN poetry install --no-interaction --no-ansi

CMD poetry run python deploy/bootstrap_admin.py && poetry run python -m slideguard.main ui run --host ${UI_HOST} --port ${UI_PORT} --auth --no-share --no-debug --hide-error --quiet --hide-api